# Trabalhando com Numpy

In [1]:
#biblioteca
import numpy as np

In [8]:
#Array de uma dimensao
vetor = np.array([4, 6, 8, 10])
vetor

array([ 4,  6,  8, 10])

In [9]:
vetor.ndim

1

In [25]:
#Array de duas dimensoes
#np.random.random([dimensao=1, linhas, colunas])
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
matriz.ndim

2

In [18]:
# Arrays de numeros aleatorios
#np.random.random([dimensao, linhas, colunas])
np.random.random([2, 5, 3])

array([[[0.88758703, 0.90623228, 0.94090031],
        [0.78342604, 0.80103702, 0.44363949],
        [0.30662834, 0.71907096, 0.97265264],
        [0.64997148, 0.37564589, 0.63548719],
        [0.02810259, 0.55741209, 0.92136425]],

       [[0.06106003, 0.20872615, 0.93975481],
        [0.40402099, 0.77481885, 0.02159608],
        [0.52201225, 0.24429638, 0.07087448],
        [0.34947103, 0.96146183, 0.10874761],
        [0.72970897, 0.30218562, 0.69666134]]])

In [19]:
#criar array de sequencias 
#start= 10, end = 50, step = 2
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [20]:
#array linear
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [24]:
#Array preenchido com zeros
np.zeros([3, 4, 8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

## Numpy Arrays vs Listas

- Arrays Numpy permitem a realização de operações em arrays inteiros de forma rápida;
- Listas não permitem operações todos os elementos da lista;
- Para operações em todos os elementos é preciso interar sobre toda a lista;
- Listas em Python armazenam diferentes tipos de objetos;
- Arrays numpy consideram todos os elementos de tipos distintos como strings.

In [26]:
#alguns exemplos
lista = [1, 2, 3]
lista * 2

[1, 2, 3, 1, 2, 3]

In [27]:
#Transformar a lista em um array numpy
lista1 = np.array(lista)
lista1 * 2

array([2, 4, 6])

In [28]:
type(lista1)

numpy.ndarray

In [33]:
# Calculo do IMC

pesos = np.array([66, 80, 130, 95])
altura = np.array([1.6, 1.7, 1.9, 1.8])

imc = pesos / altura * 2
np.round(imc, decimals=2)

array([ 82.5 ,  94.12, 136.84, 105.56])

## Métodos e Atributos

In [34]:
#shape
matriz.shape

(2, 4)

In [46]:
#dimensoes
matriz.ndim

2

In [48]:
#tamanho
matriz.size

8

In [53]:
#quantidade em bytes
matriz.itemsize

8

In [54]:
#object tipo
matriz.dtype

dtype('int64')

In [38]:
#valor maximo dentro do array
matriz.max()

8

In [39]:
#minimo
matriz.min()

1

In [43]:
#mean
matriz.mean()

4.5

In [41]:
#std
matriz.std()

2.29128784747792

In [50]:
#soma
matriz.sum()

36

## Transformação de Arrays

### Matriz transposta

In [56]:
#Nossa matriz
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
#Obter a transposta de uma matriz
matriz.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Matriz em vetor

In [60]:
new_m = matriz.reshape(-1)
new_m

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
new_m.ndim

1

### Mais sobre reshape

In [63]:
# definondo uma matriz
array3 = np.random.random([2, 5])
array3

array([[0.15179503, 0.44526047, 0.20971242, 0.20527421, 0.54388613],
       [0.58780588, 0.14761111, 0.39086703, 0.646496  , 0.53999793]])

In [65]:
array3.reshape(5, 2)

array([[0.15179503, 0.44526047],
       [0.20971242, 0.20527421],
       [0.54388613, 0.58780588],
       [0.14761111, 0.39086703],
       [0.646496  , 0.53999793]])

### Adicionar elementos na matriz

In [72]:
#modificar elementos, conforme uma posicao
matriz1 = np.insert(matriz, 2, 4)
matriz1

array([1, 2, 4, 3, 4, 5, 6, 7, 8])

In [77]:
matriz[0][2] = 100
matriz

array([[  1,   2, 100,   4],
       [  5,   6,   7,   8]])

In [102]:
#acessar colunas i linhas
#matriz[dimensao: linha, coluna]
matriz[:,3]

array([4, 8])

### Deletar elementos

In [70]:
#informe o array em que vc quer deletar, depois a poscao do elemento que se petende deletar
np.delete(matriz, [2])

array([1, 2, 4, 5, 6, 7, 8])

### Salvando em um arquivo de texto


In [103]:
np.savetxt("matriz_teste.txt", matriz, delimiter=",")

### Carregar arquivos de texto

In [105]:
new_matriz = np.loadtxt('matriz_teste.txt', delimiter =",")
new_matriz

array([[  1.,   2., 100.,   4.],
       [  5.,   6.,   7.,   8.]])